### ISSUE TITLE
[BUG] Append to statistic code in build

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#104]
**Describe the bug**
When you create a px file from build create or build update and the px file has only one statistic without a statistic code, generate a statistic code by appending C01 to the matrix code

**Comment by lorenzobruni** [comment]
Following the PX specifications, when no Statistic is explicitly defined in a PX file then the default Statistic is assumed to reference the details of the Table itself.
This is because of the structural format of the PX file itself.
On the contrary, this situation would not happen if dealing with JSON-stat where at least a Statistic (aka Metric) is mandatory.

Example of a PX file without an explicitly defined Statistic

* The default `Statistic CODE` will match the `Matrix CODE` (i.e. _DPA01_)
* The `Statistic NAME` will match the `Content` (aka first part of the Title) (i.e. _Healthy Population_)

Appending the post-fix `C01` would work in a PX file ONLY when at least one Statistic is explicitly defined.
