### ISSUE TITLE
[BUG]Safari on Load of Live

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#106]
Second error on load of live with Safari

[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (api.jsonrpc, line 0)

**Comment by liamie** [comment]
Screen Shot 2020-03-19 at 2.59.20 p.m.

**Comment by liamie** [comment]
file:///Users/formsdev/Desktop/Screen%20Shot%202020-03-19%20at%202.59.20%20p.m..png

**Comment by lorenzobruni** [comment]
This specific `401 (Unauthorized) ` error in the console is correct when browsing from the Web. The reason is that the systems probes the `private/api.json.rpc` end-point to check if the user is authorised (or not) to access the back office interface.

The web service returns correctly the `401 (Unauthorized) ` when the user in not authorised (i.e. outside of the Organisation Network)... I believe you are testing Safari from an external broadband, so that is fine.

**Comment by lorenzobruni** [comment]
Closing
