### ISSUE TITLE
[BUG] Deprecation warning

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#108]
![image](https://user-images.githubusercontent.com/55874862/77078454-82741500-69ee-11ea-852b-9d3ea7c0b8ae.png)

Occurs on opening of main data screen in both live and dev in chrome

**Comment by liamie** [comment]
Similar in Opera
![image](https://user-images.githubusercontent.com/55874862/77083650-c0c10280-69f5-11ea-932b-5a5666fcbfe1.png)

**Comment by damienderoistecso** [comment]
@lorenzobruni to investigate

**Comment by lorenzobruni** [comment]
@liamie 
The few synchronous  requests are needed to load upfront the configuration and language files which must be ready and available before any entity can use them.
Unfortunately we must live with this warning, but on the other hand only static files (fully cached/cache-able) are retrieved synchronously, so the impact is almost nothing.

By the way, I have refactored the code to use the JQuery Ajax method rather than the native JavaScript, which is more inline with the project. 

After running a update in your code, can you please test if all is still Ok cross browser?
If something goes wrong, then it should be very noticeable, as either the whole configuration and language would be missing.

Thanks

**Comment by liamie** [comment]
@lorenzobruni Can't delete Groups. Can Create and Edit fine but cannot delete.

![image](https://user-images.githubusercontent.com/55874862/77745161-b5cc2a80-7012-11ea-9cfb-c1ae9a603603.png)

**Comment by lorenzobruni** [comment]
@neilfromcork has fixed the issue. Test passed by me.
