### ISSUE TITLE
[ENHANCEMENT] Refactor of data entity 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#168]
Full regression testing of data entity required following multiple enhancements

**Comment by liamie** [comment]
Pie charts popup info for section seems to be based on left to right movement rather than section selected/highlighted or clicked.
![image](https://user-images.githubusercontent.com/55874862/88046178-9455f800-cb47-11ea-99a2-283a7d901be2.png)

**Comment by JohnPCarroll** [comment]
Table VSD20 used. Unable to see data valve when codes are set to True. Need to move the scroll bar at the botton of the pages to view data

Before codes set to true
![image](https://user-images.githubusercontent.com/44975474/88534524-2e161d00-d000-11ea-95db-3b0ccc3bb7bc.png)

After codes set to True
![image](https://user-images.githubusercontent.com/44975474/88534608-59990780-d000-11ea-8c54-4a6cc99a6f63.png)

**Comment by lorenzobruni** [comment]
This issue is caused because when the **Codes** are appended, then the table should resize accordingly but it does not.
I fixed the issue by invoking the resize window.

If the screen/window is too small for the table, then the responsiveness will kick in, see below.
Source of fix: https://datatables.net/forums/discussion/44766/responsive-doesnt-immediately-resize-the-table

@JohnPCarroll ready for testing, just do an update, thanks

**Comment by JohnPCarroll** [comment]
Test Passed
