### ISSUE TITLE
[BUG] Cookie Consent Bar disappears after clicking manage cookies link

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#229]
**Describe the bug**
The cookie consent bar disappears and does not reappear when you click on the Manage Cookies link no matter what actions are taken on the policy screen even just close.

This means that cookie consent bar is removed even without providing consent by clicking on the allow button.

![image](https://user-images.githubusercontent.com/55874862/94663529-ac918280-0301-11eb-8bbd-666d09d149b2.png)

**Comment by lorenzobruni** [comment]
Fixed... please note the following.

When you click on **Manage Cookies**, then the **Privacy** statement scrolls down to the **Cookie** section where the user can simply acknowledge the fact that non essential cookies are by default disallowed and the banner closes... otherwise there wont be an action triggered to close the banner.

Feel free to give me a call to discuss if still an issue.

P.S. Try it in Incognito, just to avoid having some cookies set.
