### ISSUE TITLE
[BUG] Live public comment not updated if deleted only

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#233]
On a live table a public comment will not update if only deleted in the release page, the old comment remains in data view.
![image](https://user-images.githubusercontent.com/55874862/94803280-f8672900-03e0-11eb-8c46-3258bfef7a7b.png)

A public comment updates to the correct information in data view if a new comment or updated comment is added in the release.

If a live public comment is deleted in release it will remain in the data view until a different update action is performed on the release page such as changing its navigation location then the previously deleted public comment will be removed also.

I don't think a secondary unrelated action should be required to update the data view after the delete step.

**Comment by lorenzobruni** [comment]
@damienderoistecso this is not a front-end issue bit rather related to a non-cleared CAS-Cache entry for a Table/Matrix.
The CAS-Cache gets correctly deleted when the Public comment is updated, but not when deleted.

I have reassigned this bug to both @liamie and @neilfromcork 

@neilfromcork can you please guide @liamie though the CAS-Cache management, so that he can work on it?

Thanks

**Comment by liamie** [comment]
Solution: Modified CAS refresh in Release DeleteComment

**Comment by JohnPCarroll** [comment]
Test passed. If a public comment is deleted it is gone from all views
