### ISSUE TITLE
[ENHANCEMENT] Render map with ChartJs library and enable widget

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#241]
**Describe the solution you'd like**
Use chartJs to render maps and enable maps to be used as widgets.

**Comment by damienderoistecso** [comment]
@liamie to test this you will also do an update of your widget dev folder. Then you will have to update lines 18 and 19 of your contstant.js file to point to your local widget code 

const C_APP_URL_PXWIDGET_ISOGRAM = "https://dev-data.cso.ie/millarl/2.6.0/widget/js/isogram.js";
const C_APP_URL_PXWIDGET_SNIPPET = "https://dev-data.cso.ie/millarl/2.6.0/widget/snippet.html";

Then do a hard re-load to make sure you are running the latest dev code

**Comment by damienderoistecso** [comment]
@liamie I have fixed a bug in the widget code so you will need to do an update of this. Please only use Chrome for now as we have a known bug for Firefox. Also test using DR123 or DR123T only as these tables have the correct map files attached to them.

**Comment by liamie** [comment]
Initially I was getting an unexpected error when going to release but that seems to have cleared.

Now visually fine going to a release but in console an error appears (may or may not be related but only occurred since changed widget stuff)
in console 
![image](https://user-images.githubusercontent.com/55874862/96007462-675b6d80-0e36-11eb-8c82-99e568956836.png)

Still no map appears when click on map tab
![image](https://user-images.githubusercontent.com/55874862/96007901-e05ac500-0e36-11eb-9cf4-6df6a406e140.png)
in widget section
![image](https://user-images.githubusercontent.com/55874862/96008004-02544780-0e37-11eb-97dc-a5df3b2c1ba2.png)

and in the console when click on map tab
![image](https://user-images.githubusercontent.com/55874862/96006970-f2883380-0e35-11eb-8e06-2bd10ba006c1.png)

**Comment by damienderoistecso** [comment]
@liamie Can you do an update on your client. Should work across all browsers now.

**Comment by liamie** [comment]
Map and widget renders correctly for the sample set provided. Tested with chrome, firefox, edge and opera.
