### ISSUE TITLE
[ENHANCEMENT] Enforce hard and soft thresholds in build create and update

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#255]
**Describe the solution you'd like**
Create hard and soft thresholds for the build.

Use in both creation of data csv files and px files across create and update. 

Soft threshold will be 1000000

Hard threshold will be 10000000

**Comment by CHanamy57** [comment]
Fixed in dev, ready for testing @JohnPCarroll

**Comment by liamie** [comment]
In build update 
The soft threshold message 
![image](https://user-images.githubusercontent.com/55874862/99073200-62144e80-25ad-11eb-8258-5e5a4339e9c3.png)
only appears if the attach csv section is used otherwise it doesn't appear if the 1000000 threshold is reached using new periods without data (auto generated)
this message appears 
![image](https://user-images.githubusercontent.com/55874862/99074240-4e69e780-25af-11eb-8118-ccdebf95ca9a.png)

but the actual update/download does not occur when confirmed

**Comment by damienderoistecso** [comment]
@lorenzobruni as discussed, bug with api.modal.confirm function in API library. Tested proposed solution locally and it works as expected. Change needs to be deployed to API client library

**Comment by lorenzobruni** [comment]
Fixed in Client API Library 4.0.5 https://github.com/CSOIreland/Client-API-Library/releases/tag/4.0.5

**Comment by lorenzobruni** [comment]
@damienderoistecso can you please test
