### ISSUE TITLE
[BUG] Add Product not working

### ISSUE THREAD

**Issue by 1026890** [CSOIreland/PxStat#30]
**Describe the bug**
When trying to add a Product clicking the Add button generates a Validation Failed modal

**To Reproduce**
1. Go to Manage | Products and select an existing Subject
2. Click Add Product
3. Enter a new Product name and click Add
4. See error - Validation failed. Please review your input.

**Expected behavior**
A new Product added to the selected Subject

**Screenshots**
![ProductInpiut](https://user-images.githubusercontent.com/54110722/71984024-f2606500-321f-11ea-9c43-9ca4a114bda2.jpg)

![ProductError](https://user-images.githubusercontent.com/54110722/71984054-00ae8100-3220-11ea-8f72-9b5f8c341a35.jpg)

**Comment by lorenzobruni** [comment]
Hi, I think this error is because you are using the latest version of the **Server** and **DB** code, but you are still using an old version of the **Client** code.
The reason I'm saying so is because the new interface to add a Product is now requiring the `Product Code` and `Product Name`.

Can you please check that you have updated also the **Client** folder with the latest code?

You can check the version of the client code by looking at the bottom corner of the footer, or otherwise inspecting the file `client/js/app.constant.js`

![image](https://user-images.githubusercontent.com/53212047/71984961-bd551200-3221-11ea-8d55-377d50601375.png)

![image](https://user-images.githubusercontent.com/53212047/71985230-0efd9c80-3222-11ea-83aa-7709682519e9.png)

**Comment by lorenzobruni** [comment]
@1026890 following our PM conversation, this bug can now be closed as invalid.
