### ISSUE TITLE
[BUG] Parse note correctly in Excel output 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#300]
**Describe the bug**
Parse BB code in note to output correctly in Excel download

**To Reproduce**
![image](https://user-images.githubusercontent.com/53211688/99971221-cd6fd480-2d94-11eb-8afd-a942aff82761.png)

**Comment by JohnPCarroll** [comment]
Note now reads as 
![image](https://user-images.githubusercontent.com/44975474/100089393-84c62300-2e49-11eb-9b2a-4f4192341980.png)

**Comment by damienderoistecso** [comment]
@neilfromcork may be related to #303

**Comment by neilfromcork** [comment]
@JohnPCarroll @damienderoistecso - Should the note on the Excel metadatab show the bbcode or the html version of the link?

**Comment by damienderoistecso** [comment]
@neilfromcork Ideal scenario would be to actually render it as a hyperlink that the users could click on. Failing that. I would think the best alternative would be to just include the href value without the link text

**Comment by neilfromcork** [comment]
Now showing the href extracted from the bbcode

**Comment by JohnPCarroll** [comment]
Used Table BBM02 in DEV.
Test failed for output note to excel. It does not contain the text or other link
![image](https://user-images.githubusercontent.com/44975474/100462375-18098d80-30c2-11eb-899b-494e7f9f1ed0.png)


Px NOTE is now correct. 

In order to reduce burden on respondents and in an attempt to streamline surveys in the CSO, the release for December 2008 reference period is the final release of this inquiry. Please see results from the Quarterly National Household Survey (QNHS) for an alternative short-term indicator concerning employment in the construction sector. For a copy of the latest QNHS release, please see the following:[url=https://www.cso.ie/en/media/csoie/releasespublications/documents/labourmarket/2011/qnhs_q42011.pdf] Quarterly National Household Survey[/url] Figures for December 2008 have been revised but amounts to no change. [url=https://www.cso.ie/en/methods/construction/indexofemploymentinconstruction/] See background notes[/url]

**Comment by lorenzobruni** [comment]
@neilfromcork 
2 problems occur now:

1. This error message shows up when opening the Excel. It looks like the XML is corrupted and the formula is somehow wrong.
![image](https://user-images.githubusercontent.com/53212047/100554733-a468ab80-328e-11eb-8da9-8d460ff7968a.png)

2. The entire note turned now into a link, rather than the individual links.
![image](https://user-images.githubusercontent.com/53212047/100554710-6f5c5900-328e-11eb-8e4b-dcd841eeeff8.png)

Can you please fix this as top priority?
Please give a call to John as soon as ready for testing.

**Comment by neilfromcork** [comment]
Fixed in DEV

**Comment by lorenzobruni** [comment]
Test passed
