### ISSUE TITLE
[BUG] Pivot param missing in PxAPIv1

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#343]
Pivoting should create a "pivot" parameter as sibling of the "format" in the API.
Same behavior of JSON-RPC, if pivoting is not specified, then no pivot occurs.

![image](https://user-images.githubusercontent.com/53212047/103761915-5d00d800-500f-11eb-8195-02fa4e15f22b.png)

**Comment by neilfromcork** [comment]
@lorenzobruni  - the pivot dimension is already included in the url rather than the body. 

We could take the view that the url should tell us the resource we're looking for and the body should tell us how we want it. Therefore maybe this should be an enhancement to move the pivot dimension from the url to the body?

**Comment by damienderoistecso** [comment]
Pivot option moved from url to POST body

**Comment by neilfromcork** [comment]
API complete. Ready for test both in 3.3.1 and 3.3.0

**Comment by lorenzobruni** [comment]
@damienderoistecso can you please test this? Thanks

**Comment by damienderoistecso** [comment]
> @damienderoistecso can you please test this? Thanks

Test passed using Postman
