### ISSUE TITLE
Adding a time period in update always appends that period. This may not be the correct position in the time dimension in some cases.

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#350]
If you add an older period to the existing data the data appears in the view in the incorrect order and also the dimensions in the time pill are incorrect as it automatically picks the first and last time point from the Px file.  Therefore the update will need to be able to re-order the data per time period (oldest period first and newest period last)

**Comment by lorenzobruni** [comment]
@neilfromcork let's review this from a business prospective

**Comment by neilfromcork** [comment]
Published in DEV - ready for test

**Comment by neilfromcork** [comment]
@JohnPCarroll - Can you hold off on testing for the moment? - I've just thought of a possible knock-on effect that must be prevented

**Comment by neilfromcork** [comment]
@JohnPCarroll - You may resume testing. Please also test for the following situation:
- An existing px file has periods out of sync (e.g. legacy situation) but is otherwise valid
- Update the px file with a new period (the new period can either be in sync or out of sync) and corresponding data
- The updated px file should contain all of the periods sorted by code and all of the data points in the correct position

**Comment by JohnPCarroll** [comment]
Test passed for the following
1. An existing px file with time periods out of sync when updated is now in the correct time point and data order.
2. Updated a px file with new time periods out of sync. The resulting px file s now in the correct time point and data order.
