### ISSUE TITLE
Using RESTful API to retrieve THA18 as CSV returns an error

### ISSUE THREAD

**Issue by olejandro** [CSOIreland/PxStat#444]
**Topic**
Using RESTful API to download a large CSV file.

**Query**
Using _**https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/THA18/CSV/1.0/en**_ returns **_The data source could not be successfully loaded: 500 Server Error: You are attempting to download 1140480 data cells in CSV. This exceeds the maximum of 1048575 data cells you can download in CSV._** What would be the best way to access this data instead?

**Comment by liamie** [comment]
You can use the a format that will provide the full dataset
https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/THA18/JSON-stat/2.0/en
https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/THA18/PX/2013/en

or 
use the filters on the table page to break the data into manageable/specific sections and download in parts
https://data.cso.ie/table/THA18 

However using the JSON-stat link above would probably be best if whole dataset is required

**Comment by lorenzobruni** [comment]
@liamie thanks for the reply 👍 

@olejandro please note that the limit of 1.048.575 is dictated by the **Microsoft Excel** constraint, hence it applies also to the **XLSX** format.
I think that @liamie observation of _slicing & dicing_ upfront and then download the CSV is probably the most efficient approach unless you really need the whole dataset.

### IMPORTANT: `PxAPIv1` is your friend too ;-)
Please note you can use the **PxAPIv1** endpoint as well, which implements a `REST` webservice rather then `RESTful`.
The main advantage of using the PxAPIv1 (aka REST) rather than the RESTful is that you can get only the selected data rather than everything. 

**See example below:**
1. Got to [https://data.cso.ie/table/THA18](https://data.cso.ie/table/THA18)
2. Let's say you want only `All engine capacity` then simply select it 
2. Scroll down to the **API Data Query** section
3. Select `CSV` from the **Format** dropdown 
4. Click on the **PxAPIv1** tab and use the `GET` or `POST` webservice that you prefer.

I hope it helps :-)
Please let us know if it is clear or we will try to help otherwise.

![image](https://user-images.githubusercontent.com/53212047/127220344-28d9d20d-7101-4282-abba-69fc0e45f913.png)

**Comment by olejandro** [comment]
Thanks a lot, @liamie and @lorenzobruni for the suggestions and a very clear explanation and example! 👍
I'll experiment with it a bit and be back in case of further questions.

**Comment by lorenzobruni** [comment]
@olejandro, that's great! 
Thanks to you for getting in touch 👍
