### ISSUE TITLE
[ENHANCEMENT] Saved queries can appear to jumble time periods compared to original due to lack of code/chronological order

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#608]
**Is your feature request related to a problem? Please describe.**
Saved queries can appear to jumble time periods and list them by alphabetical label name rather than chronological on selection arrows this means that for example June of the same year can move between May and April which can be confusing if you have set for last three months. This appears in CPM11 for example. It is not as much an issue if the code and time period label are very tightly matched eg. years only and codes both the same 2022, 2021 etc. and no named months. 

**Describe the solution you'd like**
Maintain the chronological order same as when queries are run and ordered by TLIST column in general if possible.

**Describe alternatives you've considered**
seems the TList code information is either not transferred or unused for saved queries

**Additional context**
In the original query order by month gives
![image](https://user-images.githubusercontent.com/55874862/179757393-a9fe0fac-4ee0-4f43-b648-3ab3ec88c895.png)
or
![image](https://user-images.githubusercontent.com/55874862/179757043-03f8136b-ece1-46a5-9ef7-0adc171aba53.png)

in the saved query the chronological or code  order is lost and labe alpha order seems to be used
![image](https://user-images.githubusercontent.com/55874862/179758555-f55df0b4-3f5a-4ecc-b6ac-e04f55a3320c.png)
or
![image](https://user-images.githubusercontent.com/55874862/179758222-35ee8d6d-dc2e-4230-a371-250467bdaef2.png)

**Comment by damiancosmoschapman** [comment]
I have some questions to enable me to better understand the issue.

1. The first example shown with the values 110.6, 98.7 and 118.7 does not seem to change i.e. the original and saved queries are the same. Maybe I am missing some thing here.
2. In the PxStat.Subscription.Query_API.Create API the snippet is passed in as one of the parameters to the query. The API does not change the snippet parameter. It simply saves it to the database. Is it possible that this issue is a font-end rather than a back-end issue as the back-end API takes the snippet as a parameter and saves it to the database?

**Comment by liamie** [comment]
May be related to #620

**Comment by liamie** [comment]
This seems to resolved by fix for #620
