### ISSUE TITLE
Build Create Import Inconsistency between live and dev

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#615]
Build Create Import Inconsistency between live and dev 
In current live semicolons aren't stripped from units on import
In Dev these are now stripped on import
so for the same file import different create results are produced
Dev
![image](https://user-images.githubusercontent.com/55874862/183602808-dc8b9d26-d025-428a-89e4-6154336eb35c.png)

Live
![image](https://user-images.githubusercontent.com/55874862/183602418-2e49dbe0-6f7b-4fb7-9c2a-20d6ac48bb5d.png)

ALSO 
a semicolon in Unit is allowed through by live to create the blank file but produces and error on the current DEV
![image](https://user-images.githubusercontent.com/55874862/183603456-50e74f5f-9a92-4998-b642-0797740e2866.png)

_Originally posted by @liamie in https://github.com/CSOIreland/PxStat/issues/610#issuecomment-1209081557_

**Comment by damiancosmoschapman** [comment]
The issue here is to do with what is contained in the value of the UNITS key.

In the first scenario the key value pair is:

UNITS("Consumer Price Index")="Base = 100"; 

This has the value: "Base = 100"

In the second scenario the key value pair is:

UNITS("Consumer Price Index")="Base = 100;"; 

This has the value: "Base = 100;"

According to the specification a semicolon is a valid character in the value for a UNITS key.
So the second scenario is valid. Therefore I am not going to fix this issue as according to the specification it is not an issue.

**Comment by liamie** [comment]
closed due to won't fix
