### ISSUE TITLE
[ENHANCEMENT] Change Emergency Release to Exceptional Release

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#97]
Anywhere it says Emergency Release in PXStat (and external facing) can you please amend it to say Exceptional Release

Thanks

Carol

**Comment by lorenzobruni** [comment]
Hi, the change will be implemented into 2 steps, considering that this feature is one of the main pillars of the system, controlling the **Embargo**.

### Step 1. 
Simply change the label in the **Client Side**, which is consumable by humans (only):
- from `Emergency Release` to `Exceptional Release`.
- from `Emergency` to `Exception`

### Step 2. 
Change the code and the underlying Data Model so that also machines will read e`x`ception rather than `emergency` in the API calls... otherwise there will be confusion. This is to keep consistency for data analysts, machines, developers when programmatically harvesting the datasets via APIs.

**Comment by lorenzobruni** [comment]
Both steps implemented.
@JohnPCarroll  ready for testing

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by lorenzobruni** [comment]
[BUG] Issues building Release 2.6.0 #246
